services:
    server:
        build:
            context: .
        ports:
            - 3000:3000
        environment:
            - MONGO_DB_NAME=tiler
            - MONGO_HOST=mongodb
            - MONGO_USER=/run/secrets/mongo-user
            - MONGO_PW_FILE=/run/secrets/mongo-pw
        secrets:
            - mongo-user
            - mongo-pw
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        env_file:
            - ./secrets/mongo-env.txt
        ports:
            - 27017:27017
        volumes:
            - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
            - ./mongo/db:/data/db
        secrets:
            - mongo-user
            - mongo-pw

secrets:
    mongo-pw:
        file: ./secrets/mongo-pw.txt
    mongo-user:
        file: ./secrets/mongo-user.txt
